# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@chainsafe/is-ip-2.0.1" = {
      name = "_at_chainsafe_slash_is-ip";
      packageName = "@chainsafe/is-ip";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chainsafe/is-ip/-/is-ip-2.0.1.tgz";
        sha512 = "nqSJ8u2a1Rv9FYbyI8qpDhTYujaKEyLknNrTejLYoSWmdeg+2WB7R6BZqPZYfrJzDxVi3rl6ZQuoaEvpKRZWgQ==";
      };
    };
    "@hapi/accept-6.0.0" = {
      name = "_at_hapi_slash_accept";
      packageName = "@hapi/accept";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/accept/-/accept-6.0.0.tgz";
        sha512 = "aG/Ml4kSBWCVmWvR8N8ULRuB385D8K/3OI7lquZQruH11eM7sHR5Nha30BbDzijJHtyV7Vwc6MlMwNfwb70ISg==";
      };
    };
    "@hapi/ammo-6.0.0" = {
      name = "_at_hapi_slash_ammo";
      packageName = "@hapi/ammo";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/ammo/-/ammo-6.0.0.tgz";
        sha512 = "lhX7SYtWScQaeAIL5XnE54WzyDgS5RXVeEtFEovyZcTdVzTYbo0nem56Bwko1PBcRxRUIw1v2tMb6sjFs6vEwg==";
      };
    };
    "@hapi/b64-6.0.0" = {
      name = "_at_hapi_slash_b64";
      packageName = "@hapi/b64";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/b64/-/b64-6.0.0.tgz";
        sha512 = "Es6o4BtzvMmNF28KJGuwUzUtMjF6ToZ1hQt3UOjaXc6TNkRefel+NyQSjc9b5q3Re7xwv23r0xK3Vo3yreaJHQ==";
      };
    };
    "@hapi/boom-10.0.0" = {
      name = "_at_hapi_slash_boom";
      packageName = "@hapi/boom";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/boom/-/boom-10.0.0.tgz";
        sha512 = "1YVs9tLHhypBqqinKQRqh7FUERIolarQApO37OWkzD+z6y6USi871Sv746zBPKcIOBuI6g6y4FrwX87mmJ90Gg==";
      };
    };
    "@hapi/bounce-3.0.0" = {
      name = "_at_hapi_slash_bounce";
      packageName = "@hapi/bounce";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/bounce/-/bounce-3.0.0.tgz";
        sha512 = "L0G4NcwwOYRhpcXeL76hNrLTUcObqtZMB3z4kcRVUZcR/w3v6C5Q1cTElV4/V7og1fG+wOyDR55UMFA+tWfhtA==";
      };
    };
    "@hapi/bourne-3.0.0" = {
      name = "_at_hapi_slash_bourne";
      packageName = "@hapi/bourne";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/bourne/-/bourne-3.0.0.tgz";
        sha512 = "Waj1cwPXJDucOib4a3bAISsKJVb15MKi9IvmTI/7ssVEm6sywXGjVJDhl6/umt1pK1ZS7PacXU3A1PmFKHEZ2w==";
      };
    };
    "@hapi/call-9.0.0" = {
      name = "_at_hapi_slash_call";
      packageName = "@hapi/call";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/call/-/call-9.0.0.tgz";
        sha512 = "Z6byqbEtKF3RIH2kWG6cX64RwEqHBWYEVkNoEx6oKvkPaTrC6WTPRgr+ANo9Xa8G1GXyvs/NCMTnn3Mdj12TSA==";
      };
    };
    "@hapi/catbox-12.1.0" = {
      name = "_at_hapi_slash_catbox";
      packageName = "@hapi/catbox";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/catbox/-/catbox-12.1.0.tgz";
        sha512 = "60MCN5lgaXcuRTjMZqLR+DV0clS5RAFAwfYAQU2/na6PqrXHDRQcJwVMwP7jJayCrJm4POJlLDzZLuh1ba5XUg==";
      };
    };
    "@hapi/catbox-memory-6.0.0" = {
      name = "_at_hapi_slash_catbox-memory";
      packageName = "@hapi/catbox-memory";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/catbox-memory/-/catbox-memory-6.0.0.tgz";
        sha512 = "A1O30g8GdaODx/GinytF6jFm772pdTPVWJe0cF2RiTOfhgIAAagzCcpBqRgQ8olLui0F5bzUF/SAi4BmkZ4yxA==";
      };
    };
    "@hapi/content-6.0.0" = {
      name = "_at_hapi_slash_content";
      packageName = "@hapi/content";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/content/-/content-6.0.0.tgz";
        sha512 = "CEhs7j+H0iQffKfe5Htdak5LBOz/Qc8TRh51cF+BFv0qnuph3Em4pjGVzJMkI2gfTDdlJKWJISGWS1rK34POGA==";
      };
    };
    "@hapi/cryptiles-6.0.0" = {
      name = "_at_hapi_slash_cryptiles";
      packageName = "@hapi/cryptiles";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/cryptiles/-/cryptiles-6.0.0.tgz";
        sha512 = "CUypQJI2F3HaKZjwlky3KyLu7p0O4WJXNJj+2AZ0czqwkwQIz8j+btOkzA3OMar8WTntnCrDx0f92PzxEK+JlA==";
      };
    };
    "@hapi/file-3.0.0" = {
      name = "_at_hapi_slash_file";
      packageName = "@hapi/file";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/file/-/file-3.0.0.tgz";
        sha512 = "w+lKW+yRrLhJu620jT3y+5g2mHqnKfepreykvdOcl9/6up8GrQQn+l3FRTsjHTKbkbfQFkuksHpdv2EcpKcJ4Q==";
      };
    };
    "@hapi/hapi-21.2.0" = {
      name = "_at_hapi_slash_hapi";
      packageName = "@hapi/hapi";
      version = "21.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hapi/-/hapi-21.2.0.tgz";
        sha512 = "lhidm5B2y+4cgmI9BL0xDNDJJDcHaCUUUJk8FOSuTf61JvK5HSq6zEqdAjTD+RVePpItCMLv8ZzRrdCan0Zoqw==";
      };
    };
    "@hapi/heavy-8.0.0" = {
      name = "_at_hapi_slash_heavy";
      packageName = "@hapi/heavy";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/heavy/-/heavy-8.0.0.tgz";
        sha512 = "NpKo74mF66GSwYu31IZwp11/6NmaUYxHeMTKSky09XBs8fVbzQDP83856+l+Ji6wxGmUeg75itCu1ujvEF6mdA==";
      };
    };
    "@hapi/hoek-10.0.1" = {
      name = "_at_hapi_slash_hoek";
      packageName = "@hapi/hoek";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hoek/-/hoek-10.0.1.tgz";
        sha512 = "CvlW7jmOhWzuqOqiJQ3rQVLMcREh0eel4IBnxDx2FAcK8g7qoJRQK4L1CPBASoCY6y8e6zuCy3f2g+HWdkzcMw==";
      };
    };
    "@hapi/hoek-9.3.0" = {
      name = "_at_hapi_slash_hoek";
      packageName = "@hapi/hoek";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hoek/-/hoek-9.3.0.tgz";
        sha512 = "/c6rf4UJlmHlC9b5BaNvzAcFv7HZ2QHaV0D4/HNlBdvFnvQq8RI4kYdhyPCl7Xj+oWvTWQ8ujhqS53LIgAe6KQ==";
      };
    };
    "@hapi/inert-7.0.0" = {
      name = "_at_hapi_slash_inert";
      packageName = "@hapi/inert";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/inert/-/inert-7.0.0.tgz";
        sha512 = "aJvH8rKYF42YY/XZLtq5LOWyk71GRIlcqRgvRyz+XQnj2DTdSZeerUcsxV2kyzJVm9gdemVwHp00foLfKadbMg==";
      };
    };
    "@hapi/iron-7.0.0" = {
      name = "_at_hapi_slash_iron";
      packageName = "@hapi/iron";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/iron/-/iron-7.0.0.tgz";
        sha512 = "NNXJP5fpeiTCPj/4OJG2PWBjWC0/V5D8YggS9RZeuBbfUUuTYE6TbdGqLUsCzIpPI54I8W5dhwEGbRv1CnWQtw==";
      };
    };
    "@hapi/mimos-7.0.0" = {
      name = "_at_hapi_slash_mimos";
      packageName = "@hapi/mimos";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/mimos/-/mimos-7.0.0.tgz";
        sha512 = "ALORTrZrrBPOUX05rW4htNajoekEjQtUi1PB+17/3xs/hkdQ+gSEFbs5GdJihA49qWf7td3v4PgnvOe8mcf/jQ==";
      };
    };
    "@hapi/nigel-5.0.0" = {
      name = "_at_hapi_slash_nigel";
      packageName = "@hapi/nigel";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/nigel/-/nigel-5.0.0.tgz";
        sha512 = "I9eq43BnSdz1BkvMpG7mFL7J+SIfn6DLNThuxFpIOAMUnkWbPgtcFP+HHrBAeoFkowfgQrr02vsIAkAPml4hvw==";
      };
    };
    "@hapi/pez-6.0.0" = {
      name = "_at_hapi_slash_pez";
      packageName = "@hapi/pez";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/pez/-/pez-6.0.0.tgz";
        sha512 = "3bMmsvlqrVNqaNEe4JWLZVpJ40jXuQ3vDy1+fbhyJmuAdMCMCkWexsKc7fT+mu18pFIwJzlenjc4/VE3weTq7w==";
      };
    };
    "@hapi/podium-5.0.0" = {
      name = "_at_hapi_slash_podium";
      packageName = "@hapi/podium";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/podium/-/podium-5.0.0.tgz";
        sha512 = "SbhFdu8LOIscMS82Zsoj9abcllAqbK4qBgznzJ9yr+vS2j1EomJTukkhxb76Lml0BHCd4Hn79F+3EQg06kcf8g==";
      };
    };
    "@hapi/shot-6.0.0" = {
      name = "_at_hapi_slash_shot";
      packageName = "@hapi/shot";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/shot/-/shot-6.0.0.tgz";
        sha512 = "RLGgzXy9GciJDunhY40NbVnLgYqp5gfBooZ2fOkAr4KbCEav/SJtYQS1N+knR7WFGzy8aooCR3XBUPI4ghHAkQ==";
      };
    };
    "@hapi/somever-4.1.0" = {
      name = "_at_hapi_slash_somever";
      packageName = "@hapi/somever";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/somever/-/somever-4.1.0.tgz";
        sha512 = "koNBYu7Jdcb7gaC4VcnU78rFxSlsYwuElm6NMznE0EEeznzJtvLLmDZX0SPX8kXWC/E7ONlE29HF/yiSOgWG1Q==";
      };
    };
    "@hapi/statehood-8.0.0" = {
      name = "_at_hapi_slash_statehood";
      packageName = "@hapi/statehood";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/statehood/-/statehood-8.0.0.tgz";
        sha512 = "umQTPID7BwmqAv9Rx7yLtbTNzsYg4va96aLqKneb3mlBQG32uq4iOQZ6luwBVACDFhqU3C3ewhznhukN09ZkZQ==";
      };
    };
    "@hapi/subtext-8.0.0" = {
      name = "_at_hapi_slash_subtext";
      packageName = "@hapi/subtext";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/subtext/-/subtext-8.0.0.tgz";
        sha512 = "fD+LY1U1SIUNHZJrNMIbuGl3CAd9JN8slljarFO4b8RrifkzjqbvdlZu/6iT6zlNM35GtDExf7hIepbUFUkT7A==";
      };
    };
    "@hapi/teamwork-6.0.0" = {
      name = "_at_hapi_slash_teamwork";
      packageName = "@hapi/teamwork";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/teamwork/-/teamwork-6.0.0.tgz";
        sha512 = "05HumSy3LWfXpmJ9cr6HzwhAavrHkJ1ZRCmNE2qJMihdM5YcWreWPfyN0yKT2ZjCM92au3ZkuodjBxOibxM67A==";
      };
    };
    "@hapi/topo-6.0.0" = {
      name = "_at_hapi_slash_topo";
      packageName = "@hapi/topo";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/topo/-/topo-6.0.0.tgz";
        sha512 = "aorJvN1Q1n5xrZuA50Z4X6adI6VAM2NalIVm46ALL9LUvdoqhof3JPY69jdJH8asM3PsWr2SUVYzp57EqUP41A==";
      };
    };
    "@hapi/validate-2.0.0" = {
      name = "_at_hapi_slash_validate";
      packageName = "@hapi/validate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/validate/-/validate-2.0.0.tgz";
        sha512 = "w5m8MvBgqGndbMIB+AWmXTb8CLtF1DlIxbnbAHNAo7aFuNQuI1Ywc2e0zDLK5fbFXDoqRzNrHnC7JjNJ+hDigw==";
      };
    };
    "@hapi/vise-5.0.0" = {
      name = "_at_hapi_slash_vise";
      packageName = "@hapi/vise";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/vise/-/vise-5.0.0.tgz";
        sha512 = "bz/PA7DHIvsd/2eoW7t9WpU8+k9pofZHppYEn1mCTOVnC/cGN3hCEYaoAe6BpoeJM72iJDKZEOWvQvfgCrmzxA==";
      };
    };
    "@hapi/wreck-18.0.0" = {
      name = "_at_hapi_slash_wreck";
      packageName = "@hapi/wreck";
      version = "18.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/wreck/-/wreck-18.0.0.tgz";
        sha512 = "Yk9STxoM06Hjjq58cH0KFG91u9F2h9eVE72o8vUr3AfK80qt7I2POG5+cDGTEntbnvvzm0ERow2sjG3QsqCWUA==";
      };
    };
    "@libp2p/interface-peer-id-2.0.1" = {
      name = "_at_libp2p_slash_interface-peer-id";
      packageName = "@libp2p/interface-peer-id";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@libp2p/interface-peer-id/-/interface-peer-id-2.0.1.tgz";
        sha512 = "k01hKHTAZWMOiBC+yyFsmBguEMvhPkXnQtqLtFqga2fVZu8Zve7zFAtQYLhQjeJ4/apeFtO6ddTS8mCE6hl4OA==";
      };
    };
    "@libp2p/logger-2.0.5" = {
      name = "_at_libp2p_slash_logger";
      packageName = "@libp2p/logger";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@libp2p/logger/-/logger-2.0.5.tgz";
        sha512 = "WEhxsc7+gsfuTcljI4vSgW/H2f18aBaC+JiO01FcX841Wxe9szjzHdBLDh9eqygUlzoK0LEeIBfctN7ibzus5A==";
      };
    };
    "@libp2p/webrtc-star-protocol-3.0.0" = {
      name = "_at_libp2p_slash_webrtc-star-protocol";
      packageName = "@libp2p/webrtc-star-protocol";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@libp2p/webrtc-star-protocol/-/webrtc-star-protocol-3.0.0.tgz";
        sha512 = "MavrZVQwPgyOf8ymJfzjkpFeiMkv103e4v1pmgO2/Ld0UFZWjx0CPbwpwvFcCeFMOt+O9/S3NUdxNTgkbm9gTA==";
      };
    };
    "@multiformats/multiaddr-11.3.0" = {
      name = "_at_multiformats_slash_multiaddr";
      packageName = "@multiformats/multiaddr";
      version = "11.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@multiformats/multiaddr/-/multiaddr-11.3.0.tgz";
        sha512 = "Inrmp986nHe92pgYyOWNVnB8QDmYe5EhR/7TStc46O4YEm87pbc1i4DWiTlEJ6tOpL8V6IBH5ol8BZsIaN+Tww==";
      };
    };
    "@socket.io/component-emitter-3.1.0" = {
      name = "_at_socket.io_slash_component-emitter";
      packageName = "@socket.io/component-emitter";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@socket.io/component-emitter/-/component-emitter-3.1.0.tgz";
        sha512 = "+9jVqKhRSpsc591z5vX+X5Yyw+he/HCB4iQ/RYxw35CEPaY1gnsNE43nf9n9AaYjAQrTiI/mOwKUKdUs9vf7Xg==";
      };
    };
    "@types/cookie-0.4.1" = {
      name = "_at_types_slash_cookie";
      packageName = "@types/cookie";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cookie/-/cookie-0.4.1.tgz";
        sha512 = "XW/Aa8APYr6jSVVA1y/DEIZX0/GMKLEVekNG727R8cs56ahETkRAy/3DR7+fJyh7oUgGwNQaRfXCun0+KbWY7Q==";
      };
    };
    "@types/cors-2.8.13" = {
      name = "_at_types_slash_cors";
      packageName = "@types/cors";
      version = "2.8.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cors/-/cors-2.8.13.tgz";
        sha512 = "RG8AStHlUiV5ysZQKq97copd2UmVYw3/pRMLefISZ3S1hK104Cwm7iLQ3fTKx+lsUH2CE8FlLaYeEA2LSeqYUA==";
      };
    };
    "@types/node-18.11.18" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.11.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.11.18.tgz";
        sha512 = "DHQpWGjyQKSHj3ebjFI/wRKcqQcdR+MoFBygntYOZytCqNfkd2ZC4ARDJ2DQqhjH5p85Nnd3jhUJIXrszFX/JA==";
      };
    };
    "accepts-1.3.8" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz";
        sha512 = "PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw+NACSaeXEQ+NHcVF7rONl6qcaxV3Uuemwawk+7+SJLw==";
      };
    };
    "base64id-2.0.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-2.0.0.tgz";
        sha512 = "lGe34o6EHj9y3Kts9R4ZYs/Gr+6N7MCaMlIFA3F1R2O5/m7K06AxfSeO5530PEERE6/WyEg3lsuyw4GHlPZHog==";
      };
    };
    "bintrees-1.0.2" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.2.tgz";
        sha512 = "VOMgTMwjAaUG580SXn3LacVgjurrbMme7ZZNYGSSV7mmtY6QQRh0Eg3pwIcntQ77DErK1L0NxkbetjcoXzVwKw==";
      };
    };
    "bufferutil-4.0.7" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.7.tgz";
        sha512 = "kukuqc39WOHtdxtw4UScxF/WVnMFVSQVKhtx3AjZJzhd0RGZZldcrfSEbVsWWe6KNH253574cq5F+wpv0G9pJw==";
      };
    };
    "busboy-1.6.0" = {
      name = "busboy";
      packageName = "busboy";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/busboy/-/busboy-1.6.0.tgz";
        sha512 = "8SFQbg/0hQ9xy3UNTB0YEnsNBbWfhf7RtnzpL7TkBiTBRfrQ9Fxcnz7VJsleJpyp6rVLvXiuORqjlHi5q+PYuA==";
      };
    };
    "cookie-0.4.2" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.2.tgz";
        sha512 = "aSWTXFzaKWkvHO1Ny/s+ePFpvKsPnjc551iI41v3ny/ow6tBG5Vd+FuqGNhh1LxOmVzOlGUriIlOaokOvhaStA==";
      };
    };
    "cors-2.8.5" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
        sha512 = "KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "dns-over-http-resolver-2.1.1" = {
      name = "dns-over-http-resolver";
      packageName = "dns-over-http-resolver";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-over-http-resolver/-/dns-over-http-resolver-2.1.1.tgz";
        sha512 = "Lm/eXB7yAQLJ5WxlBGwYfBY7utduXPZykcSmcG6K7ozM0wrZFvxZavhT6PqI0kd/5CUTfev/RrEFQqyU4CGPew==";
      };
    };
    "engine.io-6.2.1" = {
      name = "engine.io";
      packageName = "engine.io";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io/-/engine.io-6.2.1.tgz";
        sha512 = "ECceEFcAaNRybd3lsGQKas3ZlMVjN3cyWwMP25D2i0zWfyiytVbTpRPa34qrr+FHddtpBVOmq4H/DCv1O0lZRA==";
      };
    };
    "engine.io-client-6.2.3" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-6.2.3.tgz";
        sha512 = "aXPtgF1JS3RuuKcpSrBtimSjYvrbhKW9froICH4s0F3XQWLxsKNxqzG39nnvQZQnva4CMvUK63T7shevxRyYHw==";
      };
    };
    "engine.io-parser-5.0.6" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-5.0.6.tgz";
        sha512 = "tjuoZDMAdEhVnSFleYPCtdL2GXwVTGtNjoeJd9IhIG3C1xs9uwxqRNEu5WpnDZCaozwVlK/nuQhpodhXSIMaxw==";
      };
    };
    "err-code-3.0.1" = {
      name = "err-code";
      packageName = "err-code";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-3.0.1.tgz";
        sha512 = "GiaH0KJUewYok+eeY05IIgjtAe4Yltygk9Wqp1V5yVWLdhf0hYZchRjNIT9bb0mSwRcIusT3cx7PJUf3zEIfUA==";
      };
    };
    "interface-datastore-7.0.3" = {
      name = "interface-datastore";
      packageName = "interface-datastore";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/interface-datastore/-/interface-datastore-7.0.3.tgz";
        sha512 = "6zUypd1LM2Rl8o58RgJ7stLHgqx5+9t0+XkUVAvjd3KkWCNKBknD7G+Zar5jpUGClS+IINRPTjH/8Xnc2HB39A==";
      };
    };
    "interface-store-3.0.3" = {
      name = "interface-store";
      packageName = "interface-store";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/interface-store/-/interface-store-3.0.3.tgz";
        sha512 = "FihzZamIkSPHIFw7xZAvZ77DEOSTvHt/t3HvIG7pm8lmqDIUh8/PgDsez/4Aa2091bT0sqK4tTFBcKF9TOGhtQ==";
      };
    };
    "lru-cache-7.14.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.14.1.tgz";
        sha512 = "ysxwsnTKdAx96aTRdhDOCQfDgbHnt8SK0KY8SEjO0wHinhWOFTESbjVCMPbU1uGXg/ch4lifqx0wfjOawU2+WA==";
      };
    };
    "menoetius-0.0.3" = {
      name = "menoetius";
      packageName = "menoetius";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/menoetius/-/menoetius-0.0.3.tgz";
        sha512 = "cm953AR2J/Ya3/lZNJb/gH/927c1tZ1h5uPRytZ4yxZOUwiFmHeulZu3/IT9CImJkLQ50/NEkLW/0bHbExIKEQ==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "minimist-1.2.7" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.7.tgz";
        sha512 = "bzfL1YUZsP41gmu/qjrEk0Q6i2ix/cVeAhbCbqH9u3zYutS1cLg00qhrD0M2MVdCcx4Sc0UpP2eBWo9rotpq6g==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multiformats-11.0.1" = {
      name = "multiformats";
      packageName = "multiformats";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiformats/-/multiformats-11.0.1.tgz";
        sha512 = "atWruyH34YiknSdL5yeIir00EDlJRpHzELYQxG7Iy29eCyL+VrZHpPrX5yqlik3jnuqpLpRKVZ0SGVb9UzKaSA==";
      };
    };
    "nanoid-4.0.0" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-4.0.0.tgz";
        sha512 = "IgBP8piMxe/gf73RTQx7hmnhwz0aaEXYakvqZyE302IXW3HyVNhdNGC+O2MwMAVhLEnvXlvKtGbtJf6wvHihCg==";
      };
    };
    "native-fetch-4.0.2" = {
      name = "native-fetch";
      packageName = "native-fetch";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/native-fetch/-/native-fetch-4.0.2.tgz";
        sha512 = "4QcVlKFtv2EYVS5MBgsGX5+NWKtbDbIECdUXDBGDMAZXq3Jkv9zf+y8iS7Ub8fEdga3GpYeazp9gauNqXHJOCg==";
      };
    };
    "negotiator-0.6.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.3.tgz";
        sha512 = "+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
      };
    };
    "node-gyp-build-4.6.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.6.0.tgz";
        sha512 = "NTZVKn9IylLwUzaKjkas1e4u2DLNcV4rdYagA4PWdPwW87Bi7z+BznyKSRwS/761tV/lzCGXplWsiaMjLqP2zQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "prom-client-14.1.1" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "14.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-14.1.1.tgz";
        sha512 = "hFU32q7UZQ59bVJQGUtm3I2PrJ3gWvoCkilX9sF165ks1qflhugVCeK+S1JjJYHvyt3o5kj68+q3bchormjnzw==";
      };
    };
    "receptacle-1.3.2" = {
      name = "receptacle";
      packageName = "receptacle";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/receptacle/-/receptacle-1.3.2.tgz";
        sha512 = "HrsFvqZZheusncQRiEE7GatOAETrARKV/lnfYicIm8lbvp/JQOdADOfhjBd2DajvoszEyxSM6RlAAIZgEoeu/A==";
      };
    };
    "socket.io-4.5.4" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-4.5.4.tgz";
        sha512 = "m3GC94iK9MfIEeIBfbhJs5BqFibMtkRk8ZpKwG2QwxV0m/eEhPIV4ara6XCF1LWNAus7z58RodiZlAH71U3EhQ==";
      };
    };
    "socket.io-adapter-2.4.0" = {
      name = "socket.io-adapter";
      packageName = "socket.io-adapter";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-2.4.0.tgz";
        sha512 = "W4N+o69rkMEGVuk2D/cvca3uYsvGlMwsySWV447y99gUPghxq42BxqLNMndb+a1mm/5/7NeXVQS7RLa2XyXvYg==";
      };
    };
    "socket.io-client-4.5.4" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-4.5.4.tgz";
        sha512 = "ZpKteoA06RzkD32IbqILZ+Cnst4xewU7ZYK12aS1mzHftFFjpoMz69IuhP/nL25pJfao/amoPI527KnuhFm01g==";
      };
    };
    "socket.io-parser-4.2.2" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-4.2.2.tgz";
        sha512 = "DJtziuKypFkMMHCm2uIshOYC7QaylbtzQwiMYDuCKy3OPkjLzu4B2vAhTlqipRHHzrI0NJeBAizTK7X+6m1jVw==";
      };
    };
    "streamsearch-1.1.0" = {
      name = "streamsearch";
      packageName = "streamsearch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsearch/-/streamsearch-1.1.0.tgz";
        sha512 = "Mcc5wHehp9aXz1ax6bZUyY5afg9u2rv5cqQI3mRrYkGC8rW2hM02jWuwjtL++LS5qinSyhj2QfLyNsuc+VsExg==";
      };
    };
    "tdigest-0.1.2" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.2.tgz";
        sha512 = "+G0LLgjjo9BZX2MfdvPfH+MKLCrxlXSYec5DaPYP1fe6Iyhf0/fSmJ0bFiZ1F8BT6cGXl2LpltQptzjXKWEkKA==";
      };
    };
    "uint8arrays-4.0.3" = {
      name = "uint8arrays";
      packageName = "uint8arrays";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint8arrays/-/uint8arrays-4.0.3.tgz";
        sha512 = "b+aKlI2oTnxnfeSQWV1sMacqSNxqhtXySaH6bflvONGxF8V/fT3ZlYH7z2qgGfydsvpVo4JUgM/Ylyfl2YouCg==";
      };
    };
    "undici-5.15.1" = {
      name = "undici";
      packageName = "undici";
      version = "5.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici/-/undici-5.15.1.tgz";
        sha512 = "XLk8g0WAngdvFqTI+VKfBtM4YWXgdxkf1WezC771Es0Dd+Pm1KmNx8t93WTC+Hh9tnghmVxkclU1HN+j+CvIUA==";
      };
    };
    "utf-8-validate-5.0.10" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz";
        sha512 = "Z6czzLq4u8fPOyx7TU6X3dvUZVvoJmxSQ+IcrlmagKhilxlhZgxPK6C5Jqbkw1IDUmFTM+cz9QDnnLTwDz/2gQ==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha512 = "BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
      };
    };
    "ws-8.2.3" = {
      name = "ws";
      packageName = "ws";
      version = "8.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.2.3.tgz";
        sha512 = "wBuoj1BDpC6ZQ1B7DWQBYVLphPWkm8i9Y0/3YdHjHKHiohOJ1ws+3OccDWtH+PoC9DZD5WOTrJvNbWvjS6JWaA==";
      };
    };
    "xmlhttprequest-ssl-2.0.0" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-2.0.0.tgz";
        sha512 = "QKxVRxiRACQcVuQEYFsI1hhkrMlrXHPegbbd1yn9UHOmRxY+si12nQYzri3vbzt8VdTTRviqcKxcyllFas5z2A==";
      };
    };
  };
in
{
  "@libp2p/webrtc-star-signalling-server" = nodeEnv.buildNodePackage {
    name = "_at_libp2p_slash_webrtc-star-signalling-server";
    packageName = "@libp2p/webrtc-star-signalling-server";
    version = "3.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@libp2p/webrtc-star-signalling-server/-/webrtc-star-signalling-server-3.0.0.tgz";
      sha512 = "xDQm85vLaUJL+mr8WH1kySANKJvK85U8oikovJZqY1tA0nCpCCLOLuCvOQAzkX/V9zu1CwFV7cHCIKrURLctqA==";
    };
    dependencies = [
      sources."@chainsafe/is-ip-2.0.1"
      sources."@hapi/accept-6.0.0"
      sources."@hapi/ammo-6.0.0"
      sources."@hapi/b64-6.0.0"
      sources."@hapi/boom-10.0.0"
      sources."@hapi/bounce-3.0.0"
      sources."@hapi/bourne-3.0.0"
      sources."@hapi/call-9.0.0"
      sources."@hapi/catbox-12.1.0"
      sources."@hapi/catbox-memory-6.0.0"
      sources."@hapi/content-6.0.0"
      sources."@hapi/cryptiles-6.0.0"
      sources."@hapi/file-3.0.0"
      sources."@hapi/hapi-21.2.0"
      sources."@hapi/heavy-8.0.0"
      sources."@hapi/hoek-10.0.1"
      sources."@hapi/inert-7.0.0"
      sources."@hapi/iron-7.0.0"
      sources."@hapi/mimos-7.0.0"
      sources."@hapi/nigel-5.0.0"
      sources."@hapi/pez-6.0.0"
      sources."@hapi/podium-5.0.0"
      sources."@hapi/shot-6.0.0"
      (sources."@hapi/somever-4.1.0" // {
        dependencies = [
          sources."@hapi/hoek-9.3.0"
        ];
      })
      sources."@hapi/statehood-8.0.0"
      sources."@hapi/subtext-8.0.0"
      sources."@hapi/teamwork-6.0.0"
      sources."@hapi/topo-6.0.0"
      sources."@hapi/validate-2.0.0"
      sources."@hapi/vise-5.0.0"
      sources."@hapi/wreck-18.0.0"
      sources."@libp2p/interface-peer-id-2.0.1"
      sources."@libp2p/logger-2.0.5"
      sources."@libp2p/webrtc-star-protocol-3.0.0"
      sources."@multiformats/multiaddr-11.3.0"
      sources."@socket.io/component-emitter-3.1.0"
      sources."@types/cookie-0.4.1"
      sources."@types/cors-2.8.13"
      sources."@types/node-18.11.18"
      sources."accepts-1.3.8"
      sources."base64id-2.0.0"
      sources."bintrees-1.0.2"
      sources."bufferutil-4.0.7"
      sources."busboy-1.6.0"
      sources."cookie-0.4.2"
      sources."cors-2.8.5"
      sources."debug-4.3.4"
      sources."dns-over-http-resolver-2.1.1"
      sources."engine.io-6.2.1"
      sources."engine.io-client-6.2.3"
      sources."engine.io-parser-5.0.6"
      sources."err-code-3.0.1"
      sources."interface-datastore-7.0.3"
      sources."interface-store-3.0.3"
      sources."lru-cache-7.14.1"
      sources."menoetius-0.0.3"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimist-1.2.7"
      sources."ms-2.1.2"
      sources."multiformats-11.0.1"
      sources."nanoid-4.0.0"
      sources."native-fetch-4.0.2"
      sources."negotiator-0.6.3"
      sources."node-gyp-build-4.6.0"
      sources."object-assign-4.1.1"
      sources."prom-client-14.1.1"
      sources."receptacle-1.3.2"
      sources."socket.io-4.5.4"
      sources."socket.io-adapter-2.4.0"
      sources."socket.io-client-4.5.4"
      sources."socket.io-parser-4.2.2"
      sources."streamsearch-1.1.0"
      sources."tdigest-0.1.2"
      sources."uint8arrays-4.0.3"
      sources."undici-5.15.1"
      sources."utf-8-validate-5.0.10"
      sources."varint-6.0.0"
      sources."vary-1.1.2"
      sources."ws-8.2.3"
      sources."xmlhttprequest-ssl-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "signalling server to use with the libp2p WebRTC transport";
      homepage = "https://github.com/libp2p/js-libp2p-webrtc-star/tree/master/packages/webrtc-star-signalling-server#readme";
      license = "Apache-2.0 OR MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
