version: "3.3"
services:

    star:
        image: libp2p/js-libp2p-webrtc-star
        container_name: "star"
        environment:
            - VIRTUAL_HOST="star.bunnymen.delvelabs.xyz"
            - LETSENCRYPT_HOST="star.bunnymen.delvelabs.xyz"
            - VIRTUAL_PORT=9090
        networks:
            service_network:

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: "nginx-proxy"
        ports:
            - 443:443
            - 80:80
        container_name: nginx-proxy
        networks:
            service_network:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html
        depends_on:
            - star

    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: "nginx-proxy-letsencrypt"
        environment:
            NGINX_PROXY_CONTAINER: "nginx-proxy"
        networks:
            service_network:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html

networks:
    service_network:

volumes:
    nginx-certs:
    nginx-vhost:
    nginx-html:
